spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/invdb
    username: postgres
    password: testuser
  flyway:
    url: jdbc:postgresql://localhost:5436/invdb
    user: postgres
    password: testuser
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**/*.*
  web:
    resources:
      add-mappings: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true

pn:
  log:
    file: C:/pn

  jwt:
    timeout: 60
    issuer: com.tsone
    key: secret